version: '3'

volumes:
    db-store:
      name: ${SCHEMA}-db-store
    redis-store:
      name: ${SCHEMA}-redis-store

services:

    # webコンテナ
    web:
        build:
            context: .
            dockerfile: ./web/Dockerfile
        container_name: ${SCHEMA}-web
        hostname: ${SCHEMA}-web
        ports:
            - ${LOCAL_IP}:80:80
            - ${LOCAL_IP}:443:443
        volumes:
          - ../htdocs:/var/www/html
          - ./logs/web/httpd:/var/log/httpd
          - ./logs/web/php-fpm:/var/log/php-fpm
        environment:
            - "TZ=Japan"
        privileged: TRUE
        command: /sbin/init

    # DBコンテナ
    db:
        build:
            context: .
            dockerfile: "./db/Dockerfile"
        container_name: ${SCHEMA}-db
        ports:
            - ${LOCAL_IP}:3306:3306
        volumes:
            - db-store:/var/lib/mysql
            - ./db/cnf/:/etc/mysql/conf.d/
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER_NAME}
            MYSQL_PASSWORD: ${DB_PASS}
            TZ: "Asia/Tokyo"

    # redisコンテナ
    redis:
        image: "redis:6.2"
        container_name: ${SCHEMA}-redis
        ports:
            - ${LOCAL_IP}:6379:6379
        volumes:
            - redis-store:/data
